name: Flutter Build

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.3'
          #flutter-version: '2.0.6'
          #flutter-version: '1.22.6'
          #dart-version: '2.12.0'
          # no working: '3.19.6'
          # '2.5.3'  # Adjust Flutter version as needed
          
      - name: Disable google analytics
        run: flutter config --no-analytics
      
      - name: Check Dart version  
        run: dart --version

      - name: Build APK
        working-directory: example  # Specify the working directory
        run: flutter build apk -t lib/main.dart  # Adjust the path to your Dart file if necessary
